apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: my-app
spec:
  type: ClusterIP
  ports:
  - port: 5672
    name: amqp
  - port: 15672
    name: management
  selector:
    app: rabbitmq
